### ISSUE TITLE
Exception in thread `main`

### ISSUE THREAD

**Issue by mactsouk** [ensozos/Matrix-Profile#21]
When trying to use `getMPdistance()`, I get the following error:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.nd4j.linalg.api.ndarray.INDArray org.nd4j.linalg.factory.Nd4j.zeros(long, long)'
	at io.github.ensozos.core.MPdistance.getMassDistMatrix(MPdistance.java:116)
	at io.github.ensozos.core.MPdistance.getMPdistance(MPdistance.java:52)
	at Main.Main.main(Main.java:29)
```

I suppose it is an error related to `org.nd4j.linalg.api.ndarray.INDArray` not having an `zeros(long, long)` method but I am not proficient in Java in order to search it more.
Any ideas on what to do with it?

Thanks!

**Comment by mactsouk** [comment]
Please read [this](https://stackoverflow.com/questions/68301619/org-nd4j-linalg-factory-nd4j-zeroslong-long) in case it helps.

**Comment by ensozos** [comment]
Hi @mactsouk. Yes, we need to update the version of the ND4j to 7. I will probably do that next week. If you need that earlier, you can fork the library, update the dependencies and pr. I will be happy to answer any of your questions about the lib.

**Comment by mactsouk** [comment]
Thanks @ensozos - should you also need to push it as a *new version* at https://mvnrepository.com/artifact/io.github.ensozos/matrix-profile/?

**Comment by ensozos** [comment]
Yes, I'll have to push a new version on mvn.
