### ISSUE TITLE
Offset of buffer can not be >= Integer.MAX_VALUE

### ISSUE THREAD

**Issue by mactsouk** [ensozos/Matrix-Profile#23]
Hello.

Working with a TimeSeries of size 50.000, I got the next error message (Exception):

> Exception in thread "main" java.lang.IllegalArgumentException: Offset of buffer can not be >= Integer.MAX_VALUE
>        at org.nd4j.linalg.api.ndarray.BaseNDArray.offset(BaseNDArray.java:5216)
>        at org.nd4j.linalg.api.ndarray.BaseNDArray.subArray(BaseNDArray.java:2558)
>        at org.nd4j.linalg.api.ndarray.BaseNDArray.get(BaseNDArray.java:5013)
>        at io.github.ensozos.utils.CustomOperations.centeredMovingMinimum(CustomOperations.java:67)
>        at io.github.ensozos.core.MPdistance.getMPdistance(MPdistance.java:59)
>        at Main.main(Main.java:138)

Is it a fault (restriction) of nd4j?
Is it something else?

Thanks for your time!

**Comment by ensozos** [comment]
Yes, I think it's an issue with nd4j.
